### ISSUE TITLE
plv8 issue

### ISSUE THREAD

**Issue by jacobmadsen** [stsvilik/jPath#2]
Hi there,

I really like the looks of jpath and want to try it with PostgreSQL's plv8.

It would be really great to be able to send the filter string from a browser (an angular or ember client application) directly into PostgreSQL.

I have loaded the source of https://github.com/stsvilik/jPath/blob/master/jpath.js into plv8 and is executing:

  var people = [
    {name: "John", age:26, gender:"male"},
    {name: "Steve", age:24, gender:"male"},
    {name: "Susan", age:22, gender:"female"},
    {name: "Linda", age:30, gender:"female"},
    {name: "Adam", age:32, gender:"male"}
  ];

  var match = jPath.filter(people, "*[gender==female]");

It result in an error:

ERROR:  TypeError: boolean is not a function
DETAIL:  plv8_startup() LINE 348: })(Array);

"TypeError: boolean is not a function" is the actual error. 

plv8_startup() is my bootstrap function, where the jpath source is loaded. The line number 348 is not the jpath source.
I also do "this.window = this;" to make the window variable available (jpath depend on it).

Any chance you know why this is happening?

**Comment by jacobmadsen** [comment]
https://github.com/adunstan/plv8-jpath/blob/master/lib/plv8-jpath.js showed me the way :-)

**Comment by stsvilik** [comment]
Great :) When I wrote jPath plv8 was not around so i guess some issues have came up.
