### ISSUE TITLE
Siblings

### ISSUE THREAD

**Issue by dvv** [stsvilik/jPath#3]
Hello,
I wonder how do I compare attributes of say adjacent siblings in an array?
TIA,
--Vladimir

**Comment by stsvilik** [comment]
Ideally I would like to see an example of data that you would want to evaluate. I also mentioned in "What is not here" section that there is no value comparison between members however "a ? b" validation pattern gives you access to a node which is being evaluated through "this" keyword. Perhaps you could experiment with that (first example has the scaffolding for a setup).
